$script_mysql = <<-SCRIPT
  apt-get update && \
  apt-get install -y mysql-server-5.7 && \
  mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "phpweb" do |phpweb|
    phpweb.vm.network "forwarded_port", guest: 8888, host: 8888
    phpweb.vm.network "public_network", ip: "192.168.1.25"

    phpweb.vm.provision "shell",
      inline: "apt-get update && apt-get install -y puppet"

    phpweb.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "./configs/manifests"
      puppet.manifest_file = "phpweb.pp"
    end
  end

  config.vm.define "mysqlserver" do |mysqlserver|
     mysqlserver.vm.network "public_network", ip: "192.168.15.90"

     mysqlserver.vm.provision "shell", inline: "cat /vagrant/configs/key_bionic.pub >> .ssh/authorized_keys"
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.network "public_network", ip: "192.168.15.91"

    ansible.vm.provision "shell", inline: 
      "cp /vagrant/key_bionic /home/vagrant && \
       chmod 600 /home/vagrant/key_bionic && \
       chown vagrant:vagrant /home/vagrant/key_bionic"

    ansible.vm.provision "shell", 	
      inline: "apt-get update && \
               apt-get install -y software-properties-common && \
               add-apt-repository --yes --update ppa:ansible/ansible && \
               apt-get install -y ansible"
    
    ansible.vm.provision "shell",
        inline: "ansible-playbook -i /vagrant/configs/ansible/hosts \
                  /vagrant/configs/ansible/playbook.yml"
  end

  config.vm.define "dockerhost" do |dockerhost|
    dockerhost.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
      vb.name = "ubuntu_dockerhost"
    end
    dockerhost.vm.provision "shell", inline: "apt-get update && apt-get install -y docker.io"
  end

end
