---
- name: 'Download do wordpress na versão latest'
  get_url: 
    url: 'https://wordpress.org/latest.tar.gz'
    dest: '/tmp/wordpress.tar.gz'

- name: 'Descompactando wordpress'
  unarchive: 
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www'
    remote_src: yes
  become: yes

- name: 'Copiando arquivo de configuração do wordpress'
  copy:
    dest: "{{wp_base_dir}}/wp-config.php"
    src: "{{wp_base_dir}}/wp-config-sample.php" 
    remote_src: yes
  become: yes

- name: 'Configurar as entradas do banco de dados no wp-config'
  replace:
    path: "{{wp_base_dir}}/wp-config.php" 
    regexp:  "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items: 
  - { regex: 'database_name_here', value: "{{db_name}}"}
  - { regex: 'username_here', value: "{{db_username}}"}
  - { regex: 'password_here', value: "{{db_userpass}}"}
  - { regex: 'localhost', value: "{{db_ip}}"}
  become: yes

- name: 'Configura o template do apache2 apontando para o wordpress'
  template:
    src:  'templates/000-default.conf.j2'
    dest:  '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify: 
  - restart apache2